version: "2.4"

services:
  ntfy:
    image: binwiederhier/ntfy:v2.10.0  # from https://hub.docker.com/r/binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    restart: on-failure:5
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: nobody:nobody  # from upstream alpine image
    environment:
      - TZ=Europe/Berlin    # optional: Change to your desired timezone
    volumes:
      - ./config:/etc/ntfy
    ports:
      - 80:8080
