version: "2.4"

services:
  ntfy:
    image: binwiederhier/ntfy:v2.10.0  # from https://hub.docker.com/r/binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    restart: on-failure:5
    # TODO: use limits
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: nobody:nobody  # from upstream alpine image # TODO: use user from https://github.com/binwiederhier/ntfy/pull/1052
    # TODO: try to use read_only: true . use tmpfs for cache volume
    environment:
      - TZ=Europe/Berlin    # optional: Change to your desired timezone
    env_file: .env  # put private config values there
    volumes:
      - ./config:/etc/ntfy
    networks:
      - ntfy

networks:
  ntfy:
    name: ntfy
    driver: bridge
